version: 2
updates:
  - package-ecosystem: "npm"
    directory: "src/main/web/"
    schedule:
      interval: "daily"
      time: "03:00"
      timezone: "Europe/Berlin"
    commit-message:
      prefix: "npm"
    labels:
      - "npm dependencies"
    open-pull-requests-limit: 5
    reviewers:
      - "maxschwinghammer"
    assignees:
      - "maxschwinghammer"

  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
      time: "03:00"
      timezone: "Europe/Berlin"
    commit-message:
      prefix: "maven"
    open-pull-requests-limit: 10
    reviewers:
      - "maxschwinghammer"
    assignees:
      - "maxschwinghammer"
    
