spring:
  datasource:
    url: ${DATABASE_TEST_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  error:
    whitelabel:
      enabled: true
    include-exception: false
    include-message: never
