spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.strato.de
    port: 465
    username: info@dhbwhub.de
    support-mail: info@dhbwhub.de
    password: ${SMTP_PASSWORD}
    protocol: smtp
    templates:
      path:
        "templates/"
  thymeleaf:
    enabled: false
    prefix: "templates/"
    suffix: ".html"
    cache: false
    encoding: UTF-8
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "https://localhost:8443/oauth2callback"
            scope:
              - profile
              - email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
server:
  port: 8443
  ssl:
    enabled: true
    key-store: "keystore.p12"
    key-store-password: ${KEY_STORE_PASSWORD}
    key-store-type: "PKCS12"
    key-alias: "tomcat"

#App Properties
DHBWhub:
  app:
    jwtSecret: ${JWT_SECRET}
    jwtExpirationMs: 86400000
# server:
  # error:
    # whitelabel:
      # enabled: true
    # include-exception: false
    # include-message: never
