spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true # Enabled for debug purposes
    properties:
      hibernate:
        format_sql: true # Enabled for debug purposes
  mail:
    host: smtp.strato.de
    port: 465
    username: info@dhbwhub.de
    support-mail: info@dhbwhub.de
    password: ${SMTP_PASSWORD}
    protocol: smtp
    templates:
      path:
        "templates/"
  thymeleaf:
    enabled: false
    prefix: "templates/"
    suffix: ".html"
    cache: false
    encoding: UTF-8
server:
  port: 8443
  ssl:
    enabled: true
    key-store: "keystore.p12"
    key-store-password: ${KEY_STORE_PASSWORD}
    key-store-type: "PKCS12"
    key-alias: "tomcat"
#App Properties
DHBWhub:
  app:
    jwtSecret: ${JWT_SECRET}
    jwtExpirationMs: 86400000

# server:
  # error:
    # whitelabel:
      # enabled: true
    # include-exception: false
    # include-message: never
