spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true # Enabled for debug purposes
    properties:
      hibernate:
        format_sql: true # Enabled for debug purposes
  mail:
    host: smtp.strato.de
    port: 465
    username: info@dhbwhub.de
    password: 4??!f_UG!H52yM@
    protocol: smtp
    templates:
      path:
        "templates/"
  thymeleaf:
    enabled: false
    prefix: "templates/"
    suffix: ".html"
    cache: false
    encoding: UTF-8
#App Properties
DHBWhub:
  app:
    jwtSecret: ======================DHBWhub=Spring===========================
    jwtExpirationMs: 86400000

# server:
  # error:
    # whitelabel:
      # enabled: true
    # include-exception: false
    # include-message: never
