spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true # Enabled for debug purposes
    properties:
      hibernate:
        format_sql: true # Enabled for debug purposes
  mail:
    host:
    port:
    username:
    password:
#App Properties
DHBWhub:
  app:
    jwtSecret: ======================DHBWhub=Spring===========================
    jwtExpirationMs: 86400000

# server:
  # error:
    # whitelabel:
      # enabled: true
    # include-exception: false
    # include-message: never
