spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true # Enabled for debug purposes
    properties:
      hibernate:
        format_sql: true # Enabled for debug purposes
# server:
  # error:
    # whitelabel:
      # enabled: true
    # include-exception: false
    # include-message: never
