name: Epic
description: Creating a new Epic
title: "💯 "
labels:
- epic
assignees:
body:
- type: markdown
  attributes:
  value: "## 💯 Epic\nPlease fill out the following details to help us effectively plan and execute the Epic."

- type: textarea
  id: epic-description
  attributes:
  label: Epic Description
  description: "Provide a detailed description of the Epic."
  placeholder: "This project should provide ... so that ..."
  render: markdown
  validations:
    required: true

- type: textarea
  id: acceptance-criteria
  attributes:
  label: Acceptance Criteria
  description: "What are the acceptance criteria for this Epic?"
  placeholder: "List the conditions that must be met for the Epic to be considered complete."
  render: markdown
  validations:
    required: true

footer: "Thank you for documenting this Epic. Please double-check all information before submitting."
