export interface PrivacyPolicyInterface {
    LastUpdated: string,
    Introduction: string,
    InterpretationAndDefinitions: InterpretationAndDefinitions,
    Definitions: Definitions,
    CollectingAndUsingYourPersonalData: CollectingAndUsingYourPersonalData,
    ContactUs: ContactUs
}

export interface InterpretationAndDefinitions {
    Interpretation: string,
    Definitions: string[]
}

export interface Definitions {
    Account: string,
    Company: string,
    Cookies: string,
    Country: string,
    Device: string,
    PersonalData: string,
    Service: string,
    ServiceProvider: string,
    ThirdPartyService: string,
    UsageData: string,
    Website: string,
    You: string
}

export interface CollectingAndUsingYourPersonalData {
    TypesOfDataCollected: TypesOfDataCollected,
    UsageData: UsageData,
    InformationFromThirdPartyServices: InformationFromThirdPartyServices,
    RetentionOfYourPersonalData: RetentionOfYourPersonalData,
    TransferOfYourPersonalData: TransferOfYourPersonalData,
    DeleteYourPersonalData: DeleteYourPersonalData,
    DisclosureOfYourPersonalData: DisclosureOfYourPersonalData,
    SecurityOfYourPersonalData: string,
    ChildrensPrivacy: string,
    LinksToOtherWebsites: string,
    ChangesToThisPrivacyPolicy: string
}

export interface TypesOfDataCollected {
    PersonalData: string[],
}

export interface UsageData {
    Content: string
}

export interface InformationFromThirdPartyServices {
    Content: string,
    Services: string[]
}

export interface RetentionOfYourPersonalData {
    Content: string
}

export interface TransferOfYourPersonalData {
    Content: string
}

export interface DeleteYourPersonalData {
    Content: string
}

export interface DisclosureOfYourPersonalData {
    BusinessTransactions: string,
    LawEnforcement: string,
    OtherLegalRequirements: string[]
}

export interface ContactUs {
    Content: string,
    Website: string
}

export const privacyPolicyInterface: PrivacyPolicyInterface = {
    LastUpdated: "May 13, 2024",
    Introduction: `This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
  We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the Privacy Policy Generator.`,
    InterpretationAndDefinitions: {
        Interpretation: `The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.`,
        Definitions: [
            "For the purposes of this Privacy Policy:"
        ]
    },
    Definitions: {
        Account: "Account means a unique account created for You to access our Service or parts of our Service.",
        Company: "Company (referred to as either 'the Company', 'We', 'Us' or 'Our' in this Agreement) refers to DHBWhub.",
        Cookies: "Cookies are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.",
        Country: "Country refers to: Baden-Württemberg, Germany",
        Device: "Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.",
        PersonalData: "Personal Data is any information that relates to an identified or identifiable individual.",
        Service: "Service refers to the Website.",
        ServiceProvider: "Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.",
        ThirdPartyService: "Third-party Social Media Service refers to any website or any social network website through which a User can log in or create an account to use the Service.",
        UsageData: "Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).",
        Website: "Website refers to DHBWhub, accessible from https://dhbwhub.de",
        You: "You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable."
    },
    CollectingAndUsingYourPersonalData: {
        TypesOfDataCollected: {
            PersonalData: [
                "Email address",
                "First name and last name",
                "Usage Data"
            ]
        },
        UsageData: {
            Content: `Usage Data is collected automatically when using the Service.
      Usage Data may include information such as the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.`
        },
        InformationFromThirdPartyServices: {
            Content: `The Company allows You to create an account and log in to use the Service through the following Third-party Social Media Services:`,
            Services: [
                "Google"
            ]
        },
        RetentionOfYourPersonalData: {
            Content: `The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
      The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.`
        },
        TransferOfYourPersonalData: {
            Content: `Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.
      Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.
      The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.`
        },
        DeleteYourPersonalData: {
            Content: `You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.
      Our Service may give You the ability to delete certain information about You from within the Service.
      You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us.
      Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.`
        },
        DisclosureOfYourPersonalData: {
            BusinessTransactions: `If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.`,
            LawEnforcement: `Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).`,
            OtherLegalRequirements: [
                "Comply with a legal obligation",
                "Protect and defend the rights or property of the Company",
                "Prevent or investigate possible wrongdoing in connection with the Service",
                "Protect the personal safety of Users of the Service or the public",
                "Protect against legal liability"
            ]
        },
        SecurityOfYourPersonalData: `The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.`,
        ChildrensPrivacy: `Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.
    If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.`,
        LinksToOtherWebsites: `Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.
    We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.`,
        ChangesToThisPrivacyPolicy: `We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.
    We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.
    You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.`
    },
    ContactUs: {
        Content: `If you have any questions about this Privacy Policy, you contact us:`,
        Website: "https://dhbwhub.de/Contact"
    }
};
