name: Spring CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17

      - name: Build Spring Application
        run: ./mvnw clean install

      # Weitere Schritte wie Tests und Codeanalyse können hier hinzugefügt werden.
